### ISSUE TITLE
Add support for context

### ISSUE THREAD

**Issue by apexskier** [leelynne/lock#1]
Currently, this package uses contextless AWS api calls. This means it can't include tracing context, and is leading to a bunch of orphan spans in forgeserv.

**Comment by leelynne** [comment]
@apexskier Done. Added a 3.0.0 release.

**Comment by apexskier** [comment]
It looks like the 3.0.0 release isn't working (I'm not entirely sure why - I haven't done much with go versioning)
```
go get -u github.com/leelynne/lock@v3.0.0
go get github.com/leelynne/lock@v3.0.0: github.com/leelynne/lock@v3.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```

I suspect the backwards incompatible changes require adding the the version to the import path in the go.mod?

I was able to workaround by using an unsafe version - `go get -u github.com/leelynne/lock@master`
